# Generated by Django 5.2.3 on 2025-06-17 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('EL', 'Electronics'), ('CL', 'Clothing and Fashion'), ('FD', 'Food and Beverages'), ('BT', 'Personal Care and Beauty'), ('FT', 'Furniture')], max_length=2)),
            ],
        ),
    ]
