# Generated by Django 5.2.3 on 2025-06-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductHub', '0004_productcertificate_review_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='product',
            new_name='products',
        ),
    ]
